### ISSUE TITLE
Implement methods for all classes

### ISSUE THREAD

**Issue by ateucher** [ropensci/togeojson#11]
For `geojson_json()`, `geojson_list()`, `geojson_write()`, have methods for:

- [x] SpatialPolygons
- [x] SpatialPolygonsDataFrame
- [x] SpatialPoints
- [x] SpatialPointsDataFrame
- [x] SpatialLines
- [x] SpatialLinesDataFrame
- [x] list
- [x] data.frame
- [x] numeric

**Comment by sckott** [comment]
added spatialpoints, spatialpointsdataframe, spatiallines, and spatiallinesdataframe in fb1962508bfcb12af474e11c96e513c61114486d, 07cee0b3f2389764438b1b40df1ebb17212fd4ef, d51419821b80fe6c0fe1e8e2a160c33620cd09ee, and 88f7431b88f2ba596e116d00c407df13f11cc73f

**Comment by ateucher** [comment]
Nice!
